### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Sereja3578** [pvsaintpe/yii2-log#7]
После добавления в таблицу user_document нового столбца description типа текст

const USER_DOCUMENT_TABLE = 'user_document';

    public function safeUp()
    {
        $this->addColumn(
            self::USER_DOCUMENT_TABLE,
            'description',
            $this->text()->after('number')->comment('Описание')
        );
    }

И попытке вывести данное поле в форме редактирования получилась ошибка типа not found column 1e3er43err324.description. В отладчике запроса все названия таблицы имели вид рандомного набора символов.

**Comment by pvsaintpe** [comment]
#https://github.com/pvsaintpe/yii2-log/issues/4

**Comment by pvsaintpe** [comment]
A similar problem in view in the DetailView has similar roots. #4

**Comment by pvsaintpe** [comment]
@Sereja3578 This issue has been resolved. Please check.
